/** Domain boundary for FOX/NANO XAUUSD contracts.
 * The OpenMausBot harness remains the agent runtime. This module does not
 * start turns, mount tools, or submit orders. */

export {
  AUTONOMY_LEVELS,
  AUTONOMY_NAMES,
  CHECK_STATUSES,
  DECISION_DIRECTIONS,
  DECISION_STATUSES,
  EVIDENCE_KINDS,
  EVIDENCE_QUALITIES,
  ORDER_INTENT_DIRECTIONS,
  PROVENANCE_STATUSES,
  RECONCILIATION_STATES,
  TRADING_ENVIRONMENTS,
  TRADING_ERROR_CODES,
  TRADING_EVENT_SOURCE,
  TRADING_EVENT_TYPES,
  TRADING_SCHEMA_VERSION,
  TradingDomainError,
  MARKET_FRESHNESS_STATES,
  XAUUSD_INSTRUMENT,
  XAUUSD_TIMEFRAMES,
  assertAutonomousOrdersAllowed,
  assertCredentialSlot,
  assertNoSecretFields,
  assertProvenanceForEnvironment,
  assertReplayDataset,
  assertSubmitNotBlockedByKnownSwitch,
  assertXauUsdBoundary,
  autonomyAllowsDirectSubmit,
  autonomousOrdersBlocked,
  continueInEnvironment,
  environmentBinding,
  isTradingEvent,
  orderIntentCannotExecute,
  orderIntentCannotSubmit,
  parseAutonomyState,
  parseDecision,
  parseEnvironmentBinding,
  parseEvidence,
  parseKillSwitchState,
  parseMarketSnapshot,
  parseOrderIntent,
  parsePolicyCheck,
  parseProvenanceStatus,
  parseReconciliationState,
  parseRiskCheck,
  parseTradingEnvironment,
  parseTradingEvent,
  parseVersionManifest,
  parseXauUsdContext,
  parseXauUsdInstrument,
  requireAgentRun,
  reviseImmutable,
  tradingError,
  tradingEventsAreNotRuntimeEvents,
  transitionDecision,
  unknownKillSwitchBlocks,
} from "../../../shared/trading/index.ts";

export type {
  AgentRunId,
  AutonomyLevel,
  AutonomyName,
  AutonomyState,
  CheckStatus,
  CredentialSlot,
  Decision,
  DecisionDirection,
  DecisionStatus,
  EnvironmentBinding,
  Evidence,
  EvidenceKind,
  EvidenceQuality,
  ImmutableIdentity,
  KillSwitchState,
  MarketFreshness,
  MarketSnapshot,
  OrderIntent,
  OrderIntentDirection,
  PolicyCheck,
  ProvenanceStatus,
  ReconciliationState,
  RecordId,
  RiskCheck,
  TradingEnvironment,
  TradingErrorCode,
  TradingEvent,
  TradingEventType,
  UtcTimestamp,
  VersionManifest,
  XauUsdCandle,
  XauUsdContext,
  XauUsdInstrument,
  XauUsdTimeframe,
} from "../../../shared/trading/index.ts";
